# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

COPY bin/numberServer ./numberServer

ENV NUMBERSERVER_LOGLEVEL=debug
ENV NUMBERSERVER_TERMINATIONWORD=terminate
ENV NUMBERSERVER_MESSAGELENREQUIRED=9
ENV NUMBERSERVER_REPORTPERIODICITY=5s
ENV NUMBERSERVER_LOGNAME=./numbers.log
ENV NUMBERSERVER_SERVER_MAXCONN=5
ENV NUMBERSERVER_SERVER_HOST=0.0.0.0
ENV NUMBERSERVER_SERVER_PORT=4000


EXPOSE 4000

ENTRYPOINT [ "./numberServer" ]
